branches:
    only:
      - master
      - dev
language:
  - cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
    - os: linux
      dist: focal
      compiler: clang
script:
  
  # Check version of cmake
  - cmake --version
  
  # Run the build command
  - ./compile.sh

  # Run the test command
  - ${TRAVIS_BUILD_DIR}/third_party/gtest-parallel/gtest-parallel ${TRAVIS_BUILD_DIR}/build/bin/LearnedSort_tests --repeat=5 --workers=5

notifications:  
  email:  
    on_success: never
